name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo ::set-output name=VERSION::$(node -e "console.log(require('./package.json').version)")

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
        run: |
          gh release create "v${version}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release v${version}" \
              --generate-notes
