name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release creation
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Launch app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build

      - name: Check for executable
        run: |
          $json = Get-Content package.json -Raw | ConvertFrom-Json
          $name = $json.name
          $version = $json.version
          $search_dir = "dist"
          $exe_file = "${name} Setup ${version}.exe"

          if (Test-Path "$search_dir\$exe_file") {
              Write-Output "Executable found!"
          } else {
              Write-Output "Error: Executable not found in dist directory!"
              Write-Output "Contents of variables:"
              Write-Output "Name: $name"
              Write-Output "Version: $version"
              Write-Output "exe_file: $exe_file"
              Write-Output "Contents of dist directory:"
              Get-ChildItem -Path $search_dir
              exit 1
          }

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $json = Get-Content package.json -Raw | ConvertFrom-Json
          $changelog = Get-Content Changelog.md -Raw
          $name = $json.name
          $version = $json.version
          $search_dir = "dist"
          $exe_file = "${name} Setup ${version}.exe"
          Write-Output "Contents of variables:"
          Write-Output "Name: $name"
          Write-Output "Version: $version"
          Write-Output "exe_file: $exe_file"
          Write-Output "Contents of dist directory:"
          Get-ChildItem -Path $search_dir
          gh release create v$version --title="Release v$version" --target=main --notes="$changelog" "$search_dir\$exe_file"
