name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release creation
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Launch app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build

      - name: Check for executable
        run: |
          json=$(cat package.json)
          name=$(echo "$json" | grep -o '"name": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')
          version=$(echo "$json" | grep -o '"version": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')
          search_dir="dist"
          exe_file="${name}_Setup_${version}.exe"
          if [ -f "$search_dir/$exe_file" ]; then
            echo "Executable found!"
          else
            echo "Error: Executable not found in dist directory!"
            echo "Contents of variables:"
            echo "Name: $name"
            echo "Version: $version"
            echo "Contents of dist directory:"
            ls -l "$search_dir"
            exit 1
          fi

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          json=$(cat package.json)
          NAME=$(echo "$json" | grep -o '"name": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')
          VERSION=$(echo "$json" | grep -o '"version": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')
          gh release create v$VERSION \
              --repo="" \
              --title="Release v$VERSION" \
              --target main \
              --attach="dist/$NAME Setup $VERSION.exe"
